services:
  bot:
    build: .
    volumes:
      - ./scripts:/scripts
      -  ~/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock # So we can run docker in docker
    environment:
      SCRIPTS_DIR: $PWD/scripts