name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: Build for Linux
        run: GOOS=linux go build -o app-linux ./src/
      - name: Build for macOS
        run: GOOS=darwin go build -o app-darwin ./src/
      - name: Generate commit history
        run: |
          #!/bin/bash
          echo "Changes in this release:" > commit-history.txt
          echo "" >> commit-history.txt
          git log --pretty=format:"- %s" --no-merges origin/main...HEAD >> commit-history.txt
          echo "" >> commit-history.txt
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: $(cat commit-history.txt)
          draft: false
          prerelease: false
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-linux
          path: ./app-linux
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-darwin
          path: ./app-darwin